export const themes = {
  light: {
    '--color-background': '#F0F0F7',
    '--color-primary-lighter': '#9871F5',
    '--color-primary-light': '#916BEA',
    '--color-primary': '#8257E5',
    '--color-primary-dark': '#774DD6',
    '--color-primary-darker': '#6842C2',
    '--color-secundary': '#04D361',
    '--color-secundary-dark': '#04BF58',
    '--color-title-in-primary': '#000000',
    '--color-text-in-primary': '#B799FF',
    '--color-text-title': '#32264D',
    '--color-text-complement': '#9C98A6',
    '--color-text-base': '#6A6180',
    '--color-line-in-white': '#E6E6F0',
    '--color-input-background': '#F8F8FC',
    '--color-button-text': '#FFFFFF',
    '--color-select-text': '#000000',
    '--color-box-base': '#FFFFFF',
    '--color-box-footer': '#FAFAFC',
  },
  dark: {
    '--color-background': '#222222',
    '--color-primary-lighter': '#9871F5',
    '--color-primary-light': '#916BEA',
    '--color-primary': '#8257E5',
    '--color-primary-dark': '#774DD6',
    '--color-primary-darker': '#6842C2',
    '--color-secundary': '#04D361',
    '--color-secundary-dark': '#04BF58',
    '--color-title-in-primary': '#FFFFFF',
    '--color-text-in-primary': '#D4C2FF',
    '--color-text-title': '#5F36BE',
    '--color-text-complement': '#8F68E7',
    '--color-text-base': '#AA8AF4',
    '--color-line-in-white': '#1d1d1d',
    '--color-input-background': '#414141',
    '--color-button-text': '#FFFFFF',
    '--color-select-text': '#FFFFFF',
    '--color-box-base': '#121212',
    '--color-box-footer': '#313131',
  },
};

export type ThemeName = keyof typeof themes;
export type ThemeType = typeof themes.light | typeof themes.dark;